### ISSUE TITLE
Setting program name for Oracle DB when using HikariCP with Spring

### ISSUE THREAD

**Issue by Jobarion** [brettwooldridge/HikariCP#1260]
I am trying to connect to an Oracle DB with a specific `v$session.program` parameter.
My `application.yml`
```
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:oracle:thin:@<db_host>
      driver-class-name: oracle.jdbc.OracleDriver
      username: <username>
      password: <password>
      data-source-properties:
        v$session.program: <name>
```
How would I configure data source properties using HikariCP?
