### ISSUE TITLE
HikariPool-1 - Connection is not available, request timed out after 60000ms

### ISSUE THREAD

**Issue by fengzhenxing** [brettwooldridge/HikariCP#1620]
Below is error log:

```log
Resolved [org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 60000ms.
### The error may exist in com/techin/feefee/event/mapper/EventSourceMapper.java (best guess)
### The error may involve com.techin.feefee.event.mapper.EventSourceMapper.selectOne
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 60000ms.]
```

My config info is:

```yaml
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
      maxLifetime: 900000
      idleTimeout: 60000
      connectionTimeout: 60000
      leakDetectionThreshold: 30000
```

I enabled the debug level of leak detected

```xml
<logger name="com.zaxxer.hikari" level="DEBUG"/>
```

Hikari Version is 3.2.0

From the production log, I did not found any connection leak debug info.

Help, Thanks!!!
