### ISSUE TITLE
Connection refused after DB failover for 1 out of 2 connection pools

### ISSUE THREAD

**Issue by mschwitalla** [brettwooldridge/HikariCP#1667]
Hi, we use HikariCP and observed a weird behavior of our service after a PostgreSQL db failover was executed.

Some background information.

- The failover was executed by pointing the Elastic IP to the new primary database.
- The application has 2 connection pools to the same DB with different timeout values etc.
- We are using PostgreSQL 12
- HikariCP version 3.4.5
- PostgreSQL driver version 42.2.14
- Spring Boot 2.3.2 application
- Application is running on Kubernetes

Configuration of the datasources:

```
spring:
  datasource:
    default:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/postgres
      username: ${DB_USER:postgres}
      password: ${DB_PASSWORD:postgres}
      pool-name: default
      connection-timeout: 5000
      maximum-pool-size: 10
      validation-timeout: 800
    critical-query:
      driver-class-name: ${spring.datasource.default.driver-class-name}
      jdbc-url: ${spring.datasource.default.jdbc-url}
      username: ${spring.datasource.default.username}
      password: ${spring.datasource.default.password}
      pool-name: critical-query
      maximum-pool-size: 10
      connection-timeout: 300
      validation-timeout: 250
      connection-init-sql: "set statement_timeout to '400ms'; set application_name to 'critical-ops';"
```

The problem occured on the `default` datasource, but only for 1 out of 10 pods. And on this one pod only the `default` connection pool was affected. The `critical-query` connection pool recovered quickly after the failover. The problem was only fixed once the affected pod was manually terminated after ~30min.

We got the following exceptions:

```
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.transaction.CannotCreateTransactionException: Could not open JDBC Connection for transaction; nested exception is java.sql.SQLTransientConnectionException: default - Connection is not available, request timed out after 5000ms.
...
Caused by: org.postgresql.util.PSQLException: Connection to {URL}:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
...
Caused by: java.net.ConnectException: Connection refused (Connection refused)
```

As no DNS changes were involved, the jvm cache couldn't be a problem. Additionally I would expect that both connection pools would be affected in such a scenario. The same goes for any infrastructure related issue. 

We suspect some kind of race condition or concurrency issue that leaves hikari cp in a bad state, because not all db failovers are affected. Any help would be appreciated. In case you need more information, please let me know.
