### ISSUE TITLE
Idle connections not activating during stress test

### ISSUE THREAD

**Issue by mrtrendsetters** [brettwooldridge/HikariCP#1743]
While performing Stress test of my application, I observed that my application was not consuming more than 1 connection from connection pool. Though there were idle connections in the pool, but my app used only 1 connection. As I increased stress on my application, consumption of just 1 connection started resulting in JDBC Connection unavailable and because of that I could not complete stress test of my application.

I am using Hikari CP v3.4.5 with Oracle 12c Database with below config:
```
spring:
  datasource:
    url: url
    username: username
    password: password
    driver-class: driver class name
  jpa:
    show-sql: true
    properties:
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
```

I am expecting my app to dynamically start consumption of more idle connections from pool when 1 connection is not sufficient.
I believe its config issue that the app is no able to consume other idle connections.
