### ISSUE TITLE
HikariCP  slow Sometimes on a low-load service

### ISSUE THREAD

**Issue by Blusez** [brettwooldridge/HikariCP#2007]
Environment
```
springboot:2.7.1
HikariCP version:4.0.3
JDK version     : 1.8.0_111
Database        : MySQL
```
config
```
 hikari:  
      pool-name: hikariCP
      minimum-idle: 5  
      idle-timeout: 180000  
      maximum-pool-size: 10 
      auto-commit: true   
      max-lifetime: 1800000  
      connection-timeout: 30000 
```
there are some requests that can be very slow in a service that is only a few dozen times a minute.
Try to monitor through Skywalking,there is a step: `select 1 `(Guess this is verifying whether the connection is OK) took 30ms  , found that in the time-consuming long requests.
There is no slow sql in mysql's monitoring either.
I can't find the reason, can anyone help me?
