### ISSUE TITLE
keepalive may not work?

### ISSUE THREAD

**Issue by mojodevops** [brettwooldridge/HikariCP#2101]
I use the following config in springboot project, and use tcpdump capture tcp packet, but did not find packet about keepalive.
Can someone telll why this happened? Maybe my config was wrong?
Thanks.

```
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true&characterEncoding=utf8
    username: root
    password: xxxxxx
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: HikariCP
      minimum-idle: 1
      idle-timeout: 30000
      maximum-pool-size: 10
      auto-commit: true
      keepalive-time: 10000
      max-lifetime: 180000
      connection-timeout: 3000
      connection-test-query: SELECT 1
```

os kernel
```
sudo sysctl -a | grep tcp.keep
net.ipv4.tcp_keepalive_intvl = 15
net.ipv4.tcp_keepalive_probes = 9
net.ipv4.tcp_keepalive_time = 180
```

mysql
```
[mysqld]
...
wait-timeout=300
interactive-timeout=300
```
