### ISSUE TITLE
Apparent connection leak detected error

### ISSUE THREAD

**Issue by justinsumida** [brettwooldridge/HikariCP#2227]
We recently converted to Spring Boot 3 as a major upgrade and switched from Tomcat to Hikari. We are currently running load tests and are noticing a large change in the 99th percentile of overall response time to our web service.

One thing we notice is a lot of Apparent connection leak errors, we have the leak detection threshold set at 5 seconds right now to diagnose troubles.
Our Oracle DBE reported no queries taking close to 5 seconds from his perspective in OEM.

With a major upgrade, it can very well be another issue, but with the disconnect between a leak detection to OEM reporting fast queries, Hikari is our lead we are chasing. Is there a reason that we could be seeing such long connection times?

Our current settings look like this:

```
registerMbeans: true
maximum-pool-size: 20
connection-timeout: 30000 # 30 seconds
idle-timeout: 600000 # 10 minutes
max-lifetime: 1800000 # 30 minutes
leak-detection-threshold: 5000 # 5 seconds
data-source-properties:
  oracle:
    jdbc:
      defaultConnectionValidation: LOCAL
  socketTimeout: "30"
```

Any help here would be appreciated.
