### ISSUE TITLE
maximum-pool-size of HikarCP is not affected

### ISSUE THREAD

**Issue by grassdeveloper** [brettwooldridge/HikariCP#981]
#### Environment
```
HikariCP version: 2.6.0
JDK version     : 1.8.0_112
Database        : PostgreSQL
Driver version  : 42.0.0
```
-----------------------------------------------------------------------------------------
Hi 
spring.datasource.maximum-pool-size is always effected.
spring.datasource.hikari.maximum-pool-size is not affected.

I set the following:

```
in application.yml
spring:
  datasource:
      ....
      maximum-pool-size: 10
      hikari:
          connection-timeout: 60000
          maximum-pool-size: 5
```

And then I checked the number of connection by netstat command.
There ware 10 connections. 
It seems that maximum-pool-size of hikari doesn't work.
Even if I deleted  the spring.datasource.maximum-pool-size, the
maximum-pool-size of hikari still doesn't work.

Moreover, I set the follwoing log event, but there were no log about HikariCP.
```
logging:
  level:
    ROOT: NOTE
    org.springframework: DEBUG

```

Of course, I built with the follwoing dependencies to make sure it exculded
tomcat-jdbc:
```
    compile("org.springframework.boot:spring-boot-starter-data-jpa") {
        exclude group: 'org.apache.tomcat', module: 'tomcat-jdbc'
    }
    compile("org.springframework.boot:spring-boot-starter-jdbc") {
        exclude group: 'org.apache.tomcat', module: 'tomcat-jdbc'
    }
    compile("com.zaxxer:HikariCP:2.6.0")

```

Could you help to how to find the problem?
